# Generated by Django 3.2.16 on 2022-11-07 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_auto_20221107_2112'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='slug',
            field=models.SlugField(default='your-booking', max_length=200, unique=True),
        ),
    ]
